version: "3.9"
services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: test1234
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"